### ISSUE TITLE
Add fraud filtering

### ISSUE THREAD

**Issue by fatlotus** [uchicago-sg/caravel#127]
Wow, that was fast :) We've had our first request to block a person — in this case, globarry24@gmail.com. Thoughts on the best ways to do this? @tbkissinger @georgeteo

**Comment by tbkissinger** [comment]
Maybe just blacklist them, if they try to submit again have them receive an email saying they've been blacklisted and if they wish to appeal they can email x y z and then a human will attempt to resolve?

**Comment by tbkissinger** [comment]
More generally, might be good to build in a reporting page (maybe related to the about page?) where people can submit problem email addresses
