### ISSUE TITLE
Add "no search results found" note/image

### ISSUE THREAD

**Issue by tbkissinger** [uchicago-sg/caravel#130]
Have a note or funny image pop up when no search results are found (so people don’t think it’s still loading/etc)

**Comment by fatlotus** [comment]
https://www.google.com/search?q=confused+cat&tbm=isch

Perhaps? I can't think of a way to do it that doesn't look tacky. Alternatively, https://berniesanders.com/404.

**Comment by tbkissinger** [comment]
http://imgur.com/vBMcf08

?

On Sun, Nov 15, 2015 at 12:42 PM, Jeremy Archer <notifications@github.com>
wrote:

> https://www.google.com/search?q=confused+cat&tbm=isch
>
> Perhaps? I can't think of a way to do it that doesn't look tacky.
> Alternatively, https://berniesanders.com/404.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uchicago-sg/caravel/issues/130#issuecomment-156842357>
> .
>



-- 
The University of Chicago, '16

**Comment by fatlotus** [comment]
http://imgfave-herokuapp-com.global.ssl.fastly.net/image_cache/1395064013418974_animate.gif

**Comment by fatlotus** [comment]
Closed by #151
