### ISSUE TITLE
Crop primary image for each listing?

### ISSUE THREAD

**Issue by tbkissinger** [uchicago-sg/caravel#139]
Would things look more sleek if all of the images were cropped to be the same size? Or at least when they're showing up on the main page (prior to entering the actual listing), they're automatically cropped to be square and the same size as the other images?

**Comment by fatlotus** [comment]
Yeah- we actually already do this, and I'm working on fixing the bug in #122.

**Comment by fatlotus** [comment]
Closed by #122.
