### ISSUE TITLE
List view autogenerates more listings with hipster gallery view

### ISSUE THREAD

**Issue by tbkissinger** [uchicago-sg/caravel#140]
Title says it all

**Comment by fatlotus** [comment]
Come again? Is this a new feature or a fixed old one?

**Comment by tbkissinger** [comment]
Sorry this is unclear I didn't know the words to describe what I was observing

![screen shot 2015-11-15 at 2 14 26 pm](https://cloud.githubusercontent.com/assets/4040977/11170757/399d06da-8ba3-11e5-986c-8203879bdc73.png)
![screen shot 2015-11-15 at 2 14 35 pm](https://cloud.githubusercontent.com/assets/4040977/11170758/39a3ea7c-8ba3-11e5-8ed3-26ac6b0a7958.png)

**Comment by fatlotus** [comment]
wot
oh
yeah
I know why this happens. It's my bad. I'll work on it... sometime.

**Comment by georgeteo** [comment]
Ugh. I thought I fixed this. Maybe a recent merge remerged into the old version.
