### ISSUE TITLE
Index page listing thumbnail size

### ISSUE THREAD

**Issue by georgeteo** [uchicago-sg/caravel#17]
Make all thumbnails fixed size.

Edit: Fix listings.

**Comment by georgeteo** [comment]
Assigned you because you were working on it. Let me know if you want me to work on ti.

**Comment by fatlotus** [comment]
I thought I fixed it, but my solution only works for certain screen sizes :(

I'll work on a patch; should be fairly easy.

**Comment by fatlotus** [comment]
Done!
