### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by georgeteo** [uchicago-sg/caravel#18]

**Comment by fatlotus** [comment]
Assigned because you seemed to be working on it. Feel free to unassign if you'd like.

**Comment by georgeteo** [comment]
Implemented basic session functionality.

Can register email (dummy registration), verify email, and logout of this browser. 

TODO: 
1. Implement logout of all browsers (requires storing session information for each email address)
2. Implement email functionality and piggyback to get the registration email working. (Important!)

**Comment by fatlotus** [comment]
Whoops, must've missed this one. I think (1) is a red herring; I can't remember the last time I signed out of a web site (not to mention it requires work); I could be convinced otherwise, though.

**Comment by georgeteo** [comment]
Yes (1) doesnt exist anymore.
