### ISSUE TITLE
"Images?" column displays "No" even when images are in the listing

### ISSUE THREAD

**Issue by tranv94** [uchicago-sg/caravel#181]
The "Images?" column in list mode says "No" even when the link contains links. I checked the appliance and they were working at an earlier time.

**Comment by fatlotus** [comment]
Should be an easy fix. Would you like to make a pull request for it?

**Comment by georgeteo** [comment]
Noooooo. I thought I fixed this. 

Echo Jeremy, go ahead a fix it if you want. :)

**Comment by tranv94** [comment]
I don't mind either! I'm on an hour commute back! A fix is a fix :)

**Comment by fatlotus** [comment]
Closed by #182.
