### ISSUE TITLE
Renew listing button

### ISSUE THREAD

**Issue by georgeteo** [uchicago-sg/caravel#208]

**Comment by fatlotus** [comment]
Right now edit renews the listing — but we might want to change that.

**Comment by fatlotus** [comment]
Suggestion: we only allow updates after 7 days. Thoughts?

**Comment by fatlotus** [comment]
<img width="877" alt="screen shot 2016-01-26 at 11 52 41 am" src="https://cloud.githubusercontent.com/assets/14364/12589439/52611ce8-c423-11e5-90ab-ca94308d4bb7.png">
