### ISSUE TITLE
Implement new/edit form

### ISSUE THREAD

**Issue by georgeteo** [uchicago-sg/caravel#30]

**Comment by georgeteo** [comment]
TODO (georgeteo): improve new/edit for UI. Currently a bit ugly with 5 inputs for pictures.

**Comment by fatlotus** [comment]
One of #18 #28 #36 got this (adding for x-ref).

**Comment by georgeteo** [comment]
@fatlotus: Did you accidentally get rid of the image upload in one of the changes? See /new page now. 

Also, need to add a button from main page to make new listing.

**Comment by georgeteo** [comment]
@fatlotus bump?

**Comment by fatlotus** [comment]
Yup, will do when I'm back on campus.

**Comment by fatlotus** [comment]
Yeah- I'm still thinking of how to handle file uploads.

**Comment by fatlotus** [comment]
Fixed by #90.
