### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by georgeteo** [uchicago-sg/caravel#51]
Lets have a font discussion here. 

I am not a fan of roboto. I think it's too thick. If you like roboto, can I suggest the thin100 one? 

<img width="1218" alt="screen shot 2015-09-13 at 2 55 20 pm" src="https://cloud.githubusercontent.com/assets/12107160/9839224/861e631c-5a27-11e5-9909-3711989dc26d.png">

**Comment by fatlotus** [comment]
I think that's too light. 300? That's halfway

**Comment by fatlotus** [comment]
Merged.
