### ISSUE TITLE
Add SG logo to theme

### ISSUE THREAD

**Issue by fatlotus** [uchicago-sg/caravel#65]
I believe George was working on this, but I realize you've got stuff (so feel free to reassign). Looping in @tbkissinger for opinions on the mockup.

**Comment by tbkissinger** [comment]
Is there a particular link i should be using to access the site?

On Sun, Sep 20, 2015 at 4:28 PM, Jeremy Archer <notifications@github.com>
wrote:

> Closed #65 <https://github.com/uchicago-sg/caravel/issues/65> via #66
> <https://github.com/uchicago-sg/caravel/pull/66>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uchicago-sg/caravel/issues/65#event-414276909>.
>



-- 
The University of Chicago, '16

**Comment by fatlotus** [comment]
Oh, sorry — the "live" version of the site is https://hosted-caravel.appspot.com (eventually https://marketplace.uchicago.edu).
