### ISSUE TITLE
Add icon for category to root page

### ISSUE THREAD

**Issue by fatlotus** [uchicago-sg/caravel#79]
Some candidate icons I found:

Apartments:
![apartments_0](https://cloud.githubusercontent.com/assets/14364/10092363/18410a7e-630b-11e5-9d16-6d68f3059a9e.png)
![apartments_1](https://cloud.githubusercontent.com/assets/14364/10092364/1845b0e2-630b-11e5-8bd8-d811207bf17c.png)

Appliances:
![appliances_0](https://cloud.githubusercontent.com/assets/14364/10092368/18496548-630b-11e5-8738-e1f22745e50f.png)

Bikes:
![bikes_0](https://cloud.githubusercontent.com/assets/14364/10092365/18465d9e-630b-11e5-874f-cb038c3d8021.png)
![bikes_1](https://cloud.githubusercontent.com/assets/14364/10092366/18466a28-630b-11e5-9c3b-f872cabcd186.png)
![bikes_2](https://cloud.githubusercontent.com/assets/14364/10092367/1848b058-630b-11e5-9c8b-8ddb46dab5bb.png)

Books:
![books_0](https://cloud.githubusercontent.com/assets/14364/10092369/1849f6c0-630b-11e5-8bc7-c1cc90e82d91.png)
![books_1](https://cloud.githubusercontent.com/assets/14364/10092370/184ba272-630b-11e5-932d-46fc7cc60544.png)

Cars:
![cars_0](https://cloud.githubusercontent.com/assets/14364/10092371/184e851e-630b-11e5-8aeb-e079e8d87e54.png)
![cars_1](https://cloud.githubusercontent.com/assets/14364/10092372/184f3360-630b-11e5-8151-ae15bc609e50.png)

Furniture:
![furniture_0](https://cloud.githubusercontent.com/assets/14364/10092374/18509e44-630b-11e5-81d5-b8c40d54812b.png)
![subleases_0](https://cloud.githubusercontent.com/assets/14364/10092375/18524442-630b-11e5-81c3-b70201dfb2ab.png)

Subleases:
![subleases_1](https://cloud.githubusercontent.com/assets/14364/10092373/185012a8-630b-11e5-9b66-12913794b234.png)

Opinions? @tbkissinger @georgeteo

**Comment by georgeteo** [comment]
Looks good. 

Can we make it less black?

**Comment by fatlotus** [comment]
Ah, yeah — these are vector SVGs, so they can be warped and bent in all sorts of ways. I'm thinking light grey, slightly darker than the background.

**Comment by georgeteo** [comment]
Sounds good. Let me know if you wanna take care of this. I could take care of it if you're busy.

**Comment by fatlotus** [comment]
Go right ahead!

**Comment by fatlotus** [comment]
Pull request in #89.
